name: Promote PR to Prod
description: Build a PR from stage to target branch.
title: "Release: <short description>"
labels: ["release-request"]
body:
  - type: input
    id: gh_username
    attributes:
      label: GitHub username
      placeholder: "e.g. octocat"
    validations:
      required: true

  - type: input
    id: base
    attributes:
      label: Base PRs branch (e.g. staging)
      placeholder: "staging"
    validations:
      required: true

  - type: input
    id: skip_pr
    attributes:
      label: Prod Hold (label name)
      description: "Hold out of production releases."
      value: "skip-prod"
    validations:
      required: true

  - type: input
    id: days_back
    attributes:
      label: Lookback window (days)
      placeholder: "14"
      description: "Include PRs updated within the past N days."
    validations:
      required: true

  - type: dropdown
    id: state
    attributes:
      label: PR status
      options:
        - open
        - merged
    validations:
      required: true

  - type: dropdown
    id: slack_cc
    attributes:
      label: Reviewer
      description: "Pick Slack users/teams to notify"
      multiple: true
      options:
        - "<@U03V6VD8JHL> Muj"
        - "<@U08H78BN7K3> Nai"
    validations:
      required: false

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      options:
        - label: "I own these PRs; they meet the filters."
          required: true
