name: Promote to Prod
description: Build a release from PRs authored by you that target the base branch and have your unique label.
title: "Release: <short description>"
labels: ["release-request"]
body:
  - type: input
    id: gh_username
    attributes:
      label: GitHub username
      placeholder: "e.g. octocat"
    validations:
      required: true

  - type: input
    id: base
    attributes:
      label: Base PRs branch (e.g. staging)
      placeholder: "staging"
    validations:
      required: true

  - type: input
    id: days_back
    attributes:
      label: Lookback window (days)
      placeholder: "14"
      description: "Include PRs updated within the past N days."
    validations:
      required: true

    #options: ["open", "merged"]

  - type: dropdown
    id: state
    attributes:
      label: PR status
      options:
        - open
        - merged
    validations:
      required: true

  - type: dropdown
    id: slack_cc
    attributes:
      label: Reviewer
      description: "Pick Slack users/teams to notify"
      multiple: true
      options:
        - "<@U0123AAAA> Alice"
        - "<@U0456BBBB> Bob"
    validations:
      required: false

  - type: textarea
    id: extra_prs
    attributes:
      label: Extra PR numbers or URLs to include (optional)
      placeholder: "123\nhttps://github.com/org/repo/pull/456"
    validations:
      required: false

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      options:
        - label: "I own these PRs; they meet the filters."
          required: true
