name: Enforce Merge Rules to Main

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize, edited, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write   # needed to close PR
  issues: write          # needed to comment

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Fail unless author is bot OR label present
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          REQUIRED_LABEL: release-request
        run: |
          set -euo pipefail
          PR=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")

          mapfile -t LABELS < <(gh api "repos/$REPO/issues/$PR/labels" --jq '.[].name' | tr '[:upper:]' '[:lower:]')
          echo "Author: $AUTHOR"
          echo "Labels: ${LABELS[*]}"

          if [[ "$AUTHOR" == "github-actions[bot]" ]]; then
            echo "PASS: PR opened by github-actions[bot]."; exit 0
          fi
          if printf '%s\n' "${LABELS[@]}" | grep -qx "$(echo "$REQUIRED_LABEL" | tr '[:upper:]' '[:lower:]')"; then
            echo "PASS: Label '$REQUIRED_LABEL' present."; exit 0
          fi

          echo "::error::Blocked: PRs to main must be opened by github-actions[bot] OR have label '$REQUIRED_LABEL'."
          exit 1

      - name: Comment and close PR (non-compliant)
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          gh pr comment "$PR" --body "This branch only accepts PRs opened by \`github-actions[bot]\` or labeled \`release-request\`."
          gh pr close "$PR"
