name: pr-autolabel
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - stage

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner,repo}=context.repo;
            const pr=context.payload.pull_request;
            const seg=(pr.head.ref||'').split('/')[0]?.trim().toLowerCase(); // before first '/'
            if(!seg) return;
            if((pr.labels||[]).some(l=>l.name.toLowerCase()===seg)) return; // already present
            try { await github.rest.issues.createLabel({owner,repo,name:seg,color:'ededed'});} catch {}
            await github.rest.issues.addLabels({owner,repo,issue_number:pr.number,labels:[seg]});

